### ISSUE TITLE
Installed version from hkvfewspi cannot import

### ISSUE THREAD

**Issue by raoulcollenteur** [HKV-products-services/hkvfewspy#11]
I think there is a bug in the importing of hkvfewspy. Trying import hkvfewspy when installed through pip install hkvfewspy returns an import error. So people trying to use the package might stop after the first line of code...

This bug will NOT turn up when hkvfewspi is installed as a development project in pip. Setting up a TravisCI test suite will easily detect these kind of issues.

**Comment by mattijn** [comment]
I included the `__init__.py` in the schemas folder, which resolved this issue for me. Can you please check with the new released version 0.6.1
