### ISSUE TITLE
Make geopandas import optional

### ISSUE THREAD

**Issue by raoulcollenteur** [HKV-products-services/hkvfewspy#13]
I would like to suggest to make the import/use of geopandas optional. Geopandas has a lot of dependencies that are often not needed when using hkvfewspy. Now import fails when geopandas is not correctly installed.

**Comment by mattijn** [comment]
Once funds and time become available will consider this. For now, I've mentioned in readme mentioned to first install geopandas using conda and then install hkvfewspy. Dependencies of geopandas are also numpy and pandas etc so thats nice.

**Comment by mattijn** [comment]
fixed in version `0.6.3`
