### ISSUE TITLE
Reformat code to PEP8 formatting

### ISSUE THREAD

**Issue by raoulcollenteur** [HKV-products-services/hkvfewspy#3]
I think it would improve the code-readability to format the code based on the PEP8 formatting (spacing, line length) . This generally makes it easier to read the code. Most editors provide automatic code formatting, I could do a pull request with reformatted code ?

**Comment by mattijn** [comment]
Thanks for reporting! I think I've applied PEP8 formatting now?

**Comment by mattijn** [comment]
Improved by https://github.com/HKV-products-services/hkvfewspy/pull/10
