### ISSUE TITLE
clientTimeZone as 'Etc/GMT+1' returns attribute 

### ISSUE THREAD

**Issue by raoulcollenteur** [HKV-products-services/hkvfewspy#4]
### Code

```
params = dict(
    moduleInstanceIds=[moduleInstanceId],
    parameterIds=[parameterId],
    locationIds=[locationId],
    startTime=datetime(2015, 12, 29),
    endTime=endTime,
    clientTimeZone='Etc/GMT+1',
    forecastSearchCount=1,
    convertDatum='false',
    useDisplayUnits='false',
    showThresholds='true',
    omitMissing='false',
    onlyHeaders='false',
    onlyManualEdits='false',
    showStatistics='false',
    ensembleId='',
    importFromExternalDataSource='false',
    showEnsembleMemberIds='false',
    version='1.22'
)

df, entry = pi.getTimeSeries(params, setFormat='df')
df.reset_index(inplace=True)
df = df.loc[:, ["date", "value"]].set_index("date")
df.value.plot()
```

This returns a AttributeError when plotting:

`AttributeError: 'Etc/GMT+1' object has no attribute '_transition_info`

### Possible Solution?

Setting clientTimeZone to `'Europe/Amsterdam'` solves the problem.. but I have no idea if this is FewsPy is still dealing with the timezone correctly then..

**Comment by mattijn** [comment]
Thanks for reporting! 

Delft-FEWS is internally storing its data in GMT time zone and uses ISO 8601 for timeZones. Oftenly a Delft-FEWS environment setup in the Netherlands is set to Dutch wintertime (CET, which equals to GMT+1).

To return these values (CET) as well in Python it is necessary to set the `clientTimeZone` parameter. But Python is using POSIX standard for `Etc/GMT*`, which means that everything eastwards of GMT has its sign reversed (in POSIX standard GMT-1 means GMT+1 in ISO 8601). So to retrieve the time series as CET (in both winter and summer) use `Etc/GMT-1` for the `clientTimeZone`. 

But this is not recommended. 

Delft-FEWS does not adopt the Olson/IANA timezone database, where Python does. So for you it is good possible to use `Europe/Amsterdam` to get CET including Daylight Saving (CEST).

Which is recommended. 

I included the function `setQueryParameters` to avoid using the annoying dictionary (still possible to use though). The advantage of this new function is the auto-tab completen and the `prefill_defaults` to create a dictionary object
