### ISSUE TITLE
Start Dev branch

### ISSUE THREAD

**Issue by raoulcollenteur** [HKV-products-services/hkvfewspy#5]
I think it would be a good idea to start a development branch at some point. This way we can separate developments from stable versions.

**Comment by mattijn** [comment]
Stable versions can be installed via [Pypi](https://pypi.org/project/hkvsobekpy/#history), using `pip install hkvsobekpy` or `pip install hkvsobekpy==1.3.2` for a specifc version.

This repository hosts the development version and can be installed using `pip install git+https://github.com/HKV-products-services/hkvfewspy`. If there is a PR which has conflicts with new commits than a `git rebase` could be required to resolve the conflicts before merging. Specific new elements could be developed and tested in a branch before merging.

I agree that currently there is a new Pypi release for little code change. While there is no changelog available of changes in each version. 

Lets improve this.
