### ISSUE TITLE
Don't initialize pi object in __init__.py

### ISSUE THREAD

**Issue by raoulcollenteur** [HKV-products-services/hkvfewspy#6]
It should be possible to import hkvfewspy without initializing a pi object.

And I suggest renaming the pi object to Pi, following the PEP8 naming convention for classes.

Code would then look like this:

```
import hkvfewspy as hkv
pi = hkv.Pi()
pi.setClient(wsdl='http://localhost:8081/FewsPiService/fewspiservice?wsdl')
```

Shall I do a pull request containing these changes?

**Comment by mattijn** [comment]
That make sense! Yes, please do

**Comment by raoulcollenteur** [comment]
I'll make a PR beginning of next week!

**Comment by mattijn** [comment]
Solved by https://github.com/HKV-products-services/hkvfewspy/pull/10
